name: tests_development
on:
  # push:
  #   branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
  workflow_dispatch:

jobs:
    run_tests_development:
      runs-on: ubuntu-latest
      container: node:20-bookworm
      steps:
        
      - name: clone repo
        uses: actions/checkout@v3

      - name: snet-sdk for node.js
        run: |
          cd packages/nodejs
          npm install .
          npm run build

      - name: snet-sdk for web
        run: |
          cd packages/web
          npm install .
          npm run build
